name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0-nullsafety.3
  # flutter_localizations package come with flutter sdk, not from pub.dev
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  shared_preferences: ^2.0.0-nullsafety
  path_provider: ^2.0.0-nullsafety # finding commonly used locations on the filesystem.
  video_player: ^2.0.0-nullsafety.7 # video player controller
  video_thumbnail: ^0.3.3 # generates thumbnail from video file or URL
  image_picker: ^0.7.4 # enable picking images from the image library, and taking new pictures with the camera.
  flutter_slidable: ^0.6.0-nullsafety.0 # enable list item to slide
  random_string: ^2.2.0-nullsafety # generating random ascii strings.
  mime: ^1.0.0 # working with MIME type definitions and for processing streams of MIME multipart media types.
  flutter_video_info: ^1.2.0 # get basic meta information of a video file.
  watcher: ^1.0.0
  # flushbar: # can use this to generate push notification alike UI

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Code generation support for Localization
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # - assets/intro.mp4

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
